name: Build and Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'Dockerfile'
      - '.github/workflows/push.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare aws secret files
      run: |
        echo '${{ secrets.AWS_ACCESS_KEY }}' >> aws_credentials
        echo '${{ secrets.AWS_SECRET_KEY }}' >> aws_credentials
        echo 'us-east-1' >> aws_credentials
        echo >> aws_credentials
    - name: Build the Docker image
      run: |
        docker login -u '${{ secrets.DOCKER_USERNAME }}'  -p '${{ secrets.DOCKER_PASSWORD }}'
