name: Build and Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'Dockerfile'
      - '.github/workflows/push.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_PASSWORD }}  -p ${{ secrets.DOCKER_USERNAME }}
